# Generated by Django 2.1 on 2024-02-10 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('AUDIO', 'Audio'), ('CV', 'Curriculum Vitae'), ('LOR', 'Letter of Recommendation'), ('FILE', 'Generic File')], max_length=10)),
                ('file', models.FileField(upload_to='files')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
            ],
        ),
    ]
